#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  DEMOSTRACIÓN COMPLETA - V3.0 FUNCIONES MODULARES Y COLECCIONES║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

cd "/Users/rodrigosanchez/Library/Mobile Documents/com~apple~CloudDocs/DUOC/DESARROLLO APP MOVILES I_001A/Semana 1/vet-clinic-api-kotlin"

echo "🔧 Compilando proyecto..."
kotlinc src/Main.kt src/model/*.kt src/service/*.kt src/util/*.kt -include-runtime -d vet-clinic-modular.jar 2>&1 | grep -i "error" || echo "✅ Compilación exitosa"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 TEST 1: COLECCIONES AVANZADAS - FIND (Buscar por especialidad)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Buscando veterinario con especialidad 'Cirugía'..."
echo -e "8\nCirugía\n9" | java -jar vet-clinic-modular.jar 2>&1 | grep -A 10 "BUSCAR VETERINARIO"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🗺️  TEST 2: MAP - Agenda de Veterinarios"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Mostrando agenda completa (Map de veterinarios -> citas)..."
echo -e "6\n9" | java -jar vet-clinic-modular.jar 2>&1 | grep -A 20 "AGENDA COMPLETA"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 TEST 3: ESTADÍSTICAS con sumOf"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Mostrando estadísticas (usa sumOf para contar citas)..."
echo -e "7\n9" | java -jar vet-clinic-modular.jar 2>&1 | grep -A 25 "ESTADÍSTICAS DE VETERINARIOS"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💊 TEST 4: FUNCIONES MODULARES - Registro con medicamento"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Registrando consulta con cálculo de medicamento y próxima vacunación..."
echo -e "1\nMax\nPerro\n3\n15.5\nJuan Pérez\n+56911111111\njuan@test.cl\ns\n01/01/2025\n1\nControl general\n30\n1\n01/11/2025 10:00\n1\n9" | java -jar vet-clinic-modular.jar 2>&1 | grep -A 15 "INFORMACIÓN DE MEDICAMENTO"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                 ✅ RESUMEN DE IMPLEMENTACIÓN                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✓ 1. FUNCIONES MODULARES REUTILIZABLES:"
echo "     • calcularProximaVacunacion(fecha, especie)"
echo "     • determinarDosisRecomendada(peso, edad)"
echo "     • formatearFecha(LocalDate)"
echo "     • calcularDiasHastaVacunacion(fecha)"
echo ""
echo "✓ 2. COLECCIONES AVANZADAS - FILTER:"
echo "     • obtenerVeterinariosDisponibles()"
echo "     • obtenerVeterinariosLibresEnHorario(fechaHora)"
echo "     • Filtra listas con condiciones complejas"
echo ""
echo "✓ 3. COLECCIONES AVANZADAS - FIND:"
echo "     • buscarVeterinarioPorEspecialidad(especialidad)"
echo "     • buscarVeterinarioPorNombre(nombre)"
echo "     • Retorna primer elemento que cumple condición"
echo ""
echo "✓ 4. COLECCIONES AVANZADAS - MAP:"
echo "     • mutableMapOf<String, MutableList<String>>"
echo "     • Clave: Nombre del veterinario"
echo "     • Valor: Lista de citas agendadas"
echo "     • registrarCitaEnAgenda() - Añade al Map"
echo "     • obtenerAgendaVeterinario() - Consulta Map"
echo ""
echo "✓ 5. OPERACIONES DE COLECCIONES:"
echo "     • sumOf() - Suma total de citas"
echo "     • forEach() - Itera sobre Map"
echo "     • forEachIndexed() - Itera con índice"
echo "     • filter { condición } - Filtrado funcional"
echo "     • find { condición } - Búsqueda funcional"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        🎉 TODAS LAS FUNCIONALIDADES IMPLEMENTADAS             ║"
echo "╚════════════════════════════════════════════════════════════════╝"

